// Generates the two derived token outputs from the built ESM module, so the
// CSS variables and the Tailwind preset can never drift from the TS source:
//   ② dist/tokens.css           — :root { --kf-*: value }
//   ③ dist/tailwind-preset.cjs  — { theme: { extend: { ... } } }
//
// Run after `tsup` has produced dist/index.js.
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { tokens } from "../dist/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, "../dist");

const PREFIX = "kf";

/** camelCase | PascalCase → kebab-case (fontSize → font-size). */
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

/** CSS custom-property names can't contain ".", so 0.5 → 0_5. */
const safe = (seg) => String(seg).replace(/\./g, "_");

/** Flatten a nested token group into [varSuffix, value] leaf pairs. */
function flatten(node, trail = []) {
  const out = [];
  for (const [key, value] of Object.entries(node)) {
    const next = [...trail, safe(key)];
    if (value && typeof value === "object") {
      out.push(...flatten(value, next));
    } else {
      out.push([next.join("-"), value]);
    }
  }
  return out;
}

// ② tokens.css ---------------------------------------------------------------
const lines = [];
for (const [group, node] of Object.entries(tokens)) {
  const groupSeg = kebab(group);
  for (const [suffix, value] of flatten(node)) {
    lines.push(`  --${PREFIX}-${groupSeg}-${suffix}: ${value};`);
  }
}
const css = `/* Generated by @kitforge/tokens — do not edit by hand. */\n:root {\n${lines.join(
  "\n",
)}\n}\n`;
await writeFile(resolve(dist, "tokens.css"), css, "utf8");

// ③ tailwind-preset.cjs ------------------------------------------------------
// Self-contained: embeds the values so consumers don't need a runtime require
// of the index module. Maps each group onto Tailwind's expected theme keys.
const preset = {
  theme: {
    extend: {
      colors: tokens.color,
      spacing: tokens.spacing,
      borderRadius: tokens.radius,
      borderWidth: tokens.borderWidth,
      fontFamily: {
        sans: tokens.fontFamily.sans,
        mono: tokens.fontFamily.mono,
      },
      fontSize: tokens.fontSize,
      fontWeight: tokens.fontWeight,
      lineHeight: tokens.lineHeight,
      boxShadow: tokens.shadow,
    },
  },
};
const presetFile = `// Generated by @kitforge/tokens — do not edit by hand.\nmodule.exports = ${JSON.stringify(
  preset,
  null,
  2,
)};\n`;
await writeFile(resolve(dist, "tailwind-preset.cjs"), presetFile, "utf8");

const varCount = lines.length;
console.log(
  `✓ tokens.css (${varCount} vars) + tailwind-preset.cjs written to dist/`,
);
